services:
  - type: web
    name: ai-anomaly-project
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python scripts/use_graphrag.py"
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
    pythonVersion: 3.10
