services:
  - type: web
    name: ai-anomaly-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python scripts/use_graphrag.py
    pythonVersion: 3.10
    envVars:
      - key: OPENROUTER_API_KEY
        sync: true
