services:
  - type: web
    name: ai-anomaly-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENROUTER_API_KEY
        sync: true
    runtime: python
    pythonVersion: 3.10
